dataset:
  name: MSTAR
  dataset_dir: '/root/ZYM/zym/datasets/MSTAR/SARimage/'
  image_size: 128
  n_channels: 3
  n_classes: 10
  labels: ['2S1','BRDM_2','BTR_60','D7','SN_132','SN_9563','SN_C71','T62','ZIL131','ZSU_23_4']
augmentation:
  use_random_crop: True
  use_random_horizontal_flip: False
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: True
  use_ricap: False
  use_cutmix: True
  use_label_smoothing: False
