device: cuda:0
dataset:
  name: MSTAR
  dataset_dir: '/root/ZYM/zym/datasets/MSTAR/SARimage/'
  image_size: 128
  n_channels: 3
  n_classes: 10
  #labels: ['2S1','BRDM_2','BTR_60','D7','SN_132','SN_9563','SN_C71','T62','ZIL131','ZSU_23_4']
model:
  type: mstar
  name: resnet
  init_mode: kaiming_fan_out
  resnet:
    depth: 110
    initial_channels: 16
    block_type: basic
train:
  resume: False
  use_apex: False
  seed: 3207
  precision: O0
  batch_size: 128
  subdivision: 1
  optimizer: sgd
  base_lr: 0.07
  momentum: 0.9
  nesterov: True
  weight_decay: 1e-4
  output_dir: /root/ZYM/zym/AI_S/torch_classification/experiments/mstar/resnet/exp3
  log_period: 100
  checkpoint_period: 100
  val_ratio: 0.0
  use_test_as_val: True
  use_tensorboard: True
  distributed: False
  dataloader:
    num_workers: 32
    drop_last: True
    pin_memory: False
validation:
  batch_size: 128
  dataloader:
    num_workers: 32
    drop_last: False
    pin_memory: False
scheduler:
  epochs: 300
  type: multistep
  milestones: [30,60,90,120,150,200,250,300]
  lr_decay: 0.1
augmentation:
  use_random_crop: False
  use_random_horizontal_flip: False
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: True
  use_label_smoothing: False
  random_crop:
    padding: 4
    fill: 0
    padding_mode: constant
  random_horizontal_flip:
    prob: 0.5
tensorboard:
  train_images: False
  val_images: True
  model_params: False

optim:
  adam:
    betas: (0.9,0.999)




